### ISSUE TITLE
Crash by trying to get task.

### ISSUE THREAD

**Issue by dmartinez05** [openml/openml-python#594]
#### Description
It crashing when I try to get some tasks

#### Steps/Code to Reproduce
```python
openml.tasks.get_task(1)
```
#### Expected Results
Get the flow

#### Actual Results
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/datasets/functions.py in _get_dataset_features(did_cache_dir, dataset_id)
    472     try:
--> 473         with io.open(features_file, encoding='utf8') as fh:
    474             features_xml = fh.read()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/administrator/.openml/cache/org/openml/www/datasets/1/features.xml'

During handling of the above exception, another exception occurred:

OpenMLServerException                     Traceback (most recent call last)
<ipython-input-61-ad1cd8653b53> in <module>
----> 1 openml.tasks.get_task(1)

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/tasks/functions.py in get_task(task_id)
    295         except Exception as e:
    296             openml.utils._remove_cache_dir_for_id(TASKS_CACHE_DIR_NAME, tid_cache_dir)
--> 297             raise e
    298 
    299     return task

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/tasks/functions.py in get_task(task_id)
    289         try:
    290             task = _get_task_description(task_id)
--> 291             dataset = get_dataset(task.dataset_id)
    292             class_labels = dataset.retrieve_class_labels(task.target_name)
    293             task.class_labels = class_labels

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/datasets/functions.py in get_dataset(dataset_id)
    342                 six.raise_from(PrivateDatasetError(e.message), None)
    343             else:
--> 344                 raise e
    345         finally:
    346             if remove_dataset_cache:

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/datasets/functions.py in get_dataset(dataset_id)
    334             description = _get_dataset_description(did_cache_dir, dataset_id)
    335             arff_file = _get_dataset_arff(did_cache_dir, description)
--> 336             features = _get_dataset_features(did_cache_dir, dataset_id)
    337             qualities = _get_dataset_qualities(did_cache_dir, dataset_id)
    338             remove_dataset_cache = False

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/datasets/functions.py in _get_dataset_features(did_cache_dir, dataset_id)
    474             features_xml = fh.read()
    475     except (OSError, IOError):
--> 476         features_xml = openml._api_calls._perform_api_call("data/features/%d" % dataset_id)
    477 
    478         with io.open(features_file, "w", encoding='utf8') as fh:

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/_api_calls.py in _perform_api_call(call, data, file_dictionary, file_elements, add_authentication)
     51         return _read_url_files(url, data=data, file_dictionary=file_dictionary,
     52                                file_elements=file_elements)
---> 53     return _read_url(url, data)
     54 
     55 

~/OpenMl/openml/lib/python3.6/site-packages/openml-0.7.0-py3.6.egg/openml/_api_calls.py in _read_url(url, data)
    118 
    119     if response.status_code != 200:
--> 120         raise _parse_server_exception(response, url=url)
    121     if 'Content-Encoding' not in response.headers or \
    122             response.headers['Content-Encoding'] != 'gzip':

OpenMLServerException: https://www.openml.org/api/v1/xml/data/features/1 returned code 274: No features found. Additionally, dataset processed with error
```

#### Versions
Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
NumPy 1.15.2
SciPy 1.1.0
Scikit-Learn 0.19.1
OpenML 0.7.0

**Comment by joaquinvanschoren** [comment]
The problem is this:
curl https://www.openml.org/data/v1/download/1/anneal.ARFF
curl: (18) transfer closed with 6 bytes remaining to read

So it seems that the number of bytes was not stored correctly in the database

**Comment by joaquinvanschoren** [comment]
Not fixed yet. This requires a database update.
@janvanrijn shall we just update the bytecount in the database?
@mfeurer: does it still work for you after you clear your cache?

**Comment by janvanrijn** [comment]
We encountered this issue long ago in the database. To me, it seems like a very serious problem. The byte count in the database and on the filesystem does not longer correspond for several files. 

> @janvanrijn shall we just update the bytecount in the database?

No! We discussed this before, and to state again, I would be extremely against removing the symptom without knowing the cause. 

Possible causes:
1) We lost for many files bytes on the file system (corrupted filesystem, this would be extremely bad)
2) We recorded wrong byte-count (highly unlikely)
3) Someone manipulated several files by hand (happened in the past, but I doubt it happened again)
4) When switching servers and filesystems, different encodings on a filesystem cause to have different bytecounts (still my best guess. In this case, storing a byte count would be misleading)

**Comment by nok** [comment]
@janvanrijn To protect the raw datasets (3.) you can apply read-only rights (644) (whereby the owner is a separate user).

**Comment by janvanrijn** [comment]
I am pretty sure they are already, but most of the core maintainers also have sudo rights (to be used responsibly).

**Comment by janvanrijn** [comment]
thanks for the suggestion though :)

**Comment by joaquinvanschoren** [comment]
1. Doubt it, the file seems fine?
2. It worked before. So that can't be it? 
3. I haven't touched any dataset files in the last year or so.
4. This would also be my best guess. 

In general, if we get some more help with the backend, I think we should move the datasets to an object store (or cloud service) instead of storing them as raw files. Raw files are hard to manage, especially in large numbers.

In the short term, how do we help @dmartinez05? The fact that downloading task 1 fails is very bad, even if it is an exception.

**Comment by janvanrijn** [comment]
> In the short term, how do we help @dmartinez05? The fact that downloading task 1 fails is very bad, even if it is an exception.

I would be more comfortable with removing the measured filesize from the database (and from the download header) once we have a reliable written source that option (4) is indeed plausible. I have searched for this many times, and could never find anything relevant.

**Comment by dmartinez05** [comment]
> In the short term, how do we help @dmartinez05? The fact that downloading task 1 fails is very bad, even if it is an exception.

There is no need; I just reported something that I encounter while getting some data. :)

**Comment by joaquinvanschoren** [comment]
The file has 644 permissions, last modified in September 2017.
It has 143338 bytes, database says 143344.
The only thing that `changed' is that we moved files to a new server this month.

@dmartinez05: thanks for being so forgiving :). Still, downloading task 1 is something many people will do, so I'd like to solve this soon :).

**Comment by janvanrijn** [comment]
I completely agree, and I would like to see this solved as well as soon as possible, but I would like to restate that the system will not get better if we only treat the symptom, and not the cause, and something like this might happen again, with potential bigger consequences. 
Additionally, this is by far not the only file that suffers from this 'problem'.

> The only thing that `changed' is that we moved files to a new server this month.

Not the only thing. This (and many other) files were also moved from the first server (in Leiden) to the second server (in Eindhoven). We already discovered the problem once the main server was running in Eindhoven (Hangouts does not have a good chat history, so I can't show you the chats, you have to take my word for it).

**Comment by joaquinvanschoren** [comment]
Don't worry, I remember that we discussed this before :). We didn't find the cause and left it at that, right?

The file also has 143338 bytes on the old server. So it wasn't the server move?
Maybe it was indeed changed manually a year ago and we are only now seeing issues?

> Additionally, this is by far not the only file that suffers from this 'problem'.
Can you easily test how many files we are talking about?

**Comment by janvanrijn** [comment]
> The file also has 143338 bytes on the old server. So it wasn't the server move?

I suspect it was the server move from Leiden to Eindhoven. 

> Can you easily test how many files we are talking about?

No, but I see the evaluation engine crash quite often on this with old runs. You can try this query on the database: 
`
SELECT * FROM run_evaluated WHERE error LIKE "Premature end of Content-Length%" 
`

**Comment by joaquinvanschoren** [comment]
Apparently, 73 datasets have this issue. Almost all are older datasets.

> SELECT distinct ti.value FROM run_evaluated re, run r, task_inputs ti WHERE re.run_id = r.rid and re.error LIKE "Premature end of Content-Length%" and ti.input = "source_data" and r.task_id = ti.task_id

**Comment by janvanrijn** [comment]
Interesting. Not entirely sure if it is dataset or run (predictions, description file) related. Quite possibly the datasets are the issue.

**Comment by joaquinvanschoren** [comment]
If we are reasonably sure that this because of a bad earlier file move (and this now seems plausible to me), we could test this by recomputing and storing the file sizes anew. If that was indeed the issue, that will fix the problem permanently. If the issue comes back, then we know we need to look elsewhere.

**Comment by janvanrijn** [comment]
> If we are reasonably sure that this because of a bad earlier file move (and this now seems plausible to me),

the fact that these runs are all from the same 73 datasets makes me actually doubt this

Is there a plausible explanation why exactly 73 dataset files are affected, and millions of files from the other categories (flow, run file, etc) are fine? This statistic just does not make sense to me.

**Comment by janvanrijn** [comment]
I think the best action point is to write a script that determines which files have the wrong file size (important todo, but doesn't have to happen now* as we are all busy preparing for nips). If it are indeed only the 73 datasets then my conclusion would be that someone (with good intentions) manually manipulated the datasets, fix the filesizes (and potential md5 hashes) and close the issue physically and mentally :)

**Comment by joaquinvanschoren** [comment]
This was fixed during the last OpenML hackathon. The datasets and runs were processed anew.

**Comment by terry07** [comment]
Any update on this, since neither that example runs on win11: https://github.com/openml/openml-python/blob/develop/examples/20_basic/introduction_tutorial.py

OpenMLServerException: https://test.openml.org/api/v1/xml/task/403 returned code 103: Authentication failed - None

**Comment by PGijsbers** [comment]
The authentication issue is unrelated to this (resolved issue). 
The authentication issue is due to the test server currently not being functional, as we are in the process of transferring this to a new setup.
@prabhant Any news?

**Comment by PavanKumarPerugu** [comment]
@PGijsbers Thanks for your reply here. But I can not see anyupdate with my code compilation. I am still facing the same error of Authentication as follows: ' openml.exceptions.OpenMLServerException: https://test.openml.org/api/v1/xml/task/403 returned code 103: Authentication failed - None '. 

So could you please guide me through fixing this error?

Thank you very much in advance.

**Comment by PGijsbers** [comment]
I can have a look, but please open a new issue for this. The authentication problem is unrelated to this problem. Having new issue which clearly describes the problem with steps to reproduce will be much more useful to us and any future readers that might try to find solutions to their problem. Thanks :)
